version: '3'

services:
  dtn-server-1:
    build:
      context: ./
      dockerfile: dockerfile/Dockerfile
    container_name: "dtn1"
    ports:
      - "50001:5001/tcp"
      - "50001:5001/udp"
    networks:
      - public 
      - private 
  
  dtn-server-2:
    build:
      context: ./
      dockerfile: dockerfile/Dockerfile
    container_name: "dtn2"
    ports:
      - "50002:5001/tcp"
      - "50002:5001/udp"
    networks:
      - public 
      - private 

networks:
  public:
    driver: bridge
  private:
    driver: bridge